#!/bin/bash
if [ -z "$RYTHMEPERCUSSION" ] ; then
echo "RYTHMEPERCUSSION non d´efinie"
return 1;
fi
while true;
do
echo $1 \($(date +%H:%M:%S)\);
sleep "$RYTHMEPERCUSSION";
done
Dockerfile
FROM ubuntu:latest
MAINTAINER IngeSup "doclab@ingesup.com"
COPY percussion.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENV RYTHMEPERCUSSION 2
ENTRYPOINT ["/entrypoint.sh"]
CMD ["percussion"]
108
Construction d’une Image
• Test du script par son ex´ecution sur la machine
hˆote
. ./percussion.sh bonjour
RYTHMEPERCUSSION non d´efinie
echo $?
1
• Pour un test fonctionnel
RYTHMEPERCUSSION=2 . ./percussion.sh
(12:24:57)
(12:24:59)
(12:25:01)
(12:25:03)
(12:25:05)
(12:25:07)
(12:25:09)
^C
